/** MEMORY CACHE **/
/**--------------**/
SELECT 
    NAME, 
    ROUND(CAST(PAGES_KB AS FLOAT)/1024,2) AS PAGES_MB, 
    ROUND(CAST(PAGES_KB AS FLOAT)/1024/1024,2) AS PAGES_GB 
FROM 
    SYS.DM_OS_MEMORY_CACHE_COUNTERS
WHERE 
    NAME IN ('OBJECT PLANS', 'SQL PLANS', 'BOUND TREES', 'EXTENDED STORED PROCEDURE', 'TEMPORARY TABLES & TABLE VARIABLES','SYSTEMROWSETSTORE','TEMPDB')

/**-------------------------------------------------**/

SELECT 
     SQLSERVER_START_TIME,
     ROUND(CAST(COMMITTED_KB AS FLOAT)/1024/1024,2) AS COMMITTED_GB,
     ROUND(CAST(COMMITTED_TARGET_KB AS FLOAT)/1024/1024,2) AS COMMITTED_TARGET_GB
FROM 
    SYS.DM_OS_SYS_INFO

/**-------------------------------------------------**/ 

SELECT
    DB_NAME(DATABASE_ID) AS DATABASE_NAME, COUNT(*) NUMBER_OF_CLEAN_PAGES,(COUNT(*)*8)/1024 AS SIZE_IN_MB
FROM
    SYS.DM_OS_BUFFER_DESCRIPTORS
WHERE
    IS_MODIFIED = 0
GROUP BY DATABASE_ID
ORDER BY NUMBER_OF_CLEAN_PAGES DESC

/**BASED ON ABOVE AOUTPUT USE THIS TO DROP CLEAN BUFFERS**/
/**-----------------------------------------------------**/
DBCC DROPCLEANBUFFERS


