/**TO GET THE FRAGMENTATION OF A DATABASE**/
/**--------------------------------------**/
USE [DB_NAME]
GO
SELECT 
    OBJECT_NAME(OBJECT_ID), 
    INDEX_ID, INDEX_TYPE_DESC, INDEX_LEVEL, 
    AVG_FRAGMENTATION_IN_PERCENT, AVG_PAGE_SPACE_USED_IN_PERCENT, PAGE_COUNT 
FROM 
    SYS.DM_DB_INDEX_PHYSICAL_STATS(DB_ID(N'DB_NAME'), NULL, NULL, NULL, 'SAMPLED')
ORDER BY 
    AVG_FRAGMENTATION_IN_PERCENT DESC

/**TO GET THE FRAGMENTATION OF A DATABASE**/
/**--------------------------------------**/

SELECT * 
FROM SYS.DM_DB_INDEX_PHYSICAL_STATS (NULL, NULL, NULL, NULL, NULL)  
WHERE AVG_FRAGMENTATION_IN_PERCENT > 0 
ORDER BY AVG_FRAGMENTATION_IN_PERCENT DESC; 

/**TO GET THE FRAGMENTATION OF A DATABASE**/
/**--------------------------------------**/

SELECT 
    S.NAME AS 'SCHEMA',
    T.NAME AS 'TABLE',
    I.NAME AS 'INDEX',
    DDIPS.AVG_FRAGMENTATION_IN_PERCENT,
    DDIPS.PAGE_COUNT
FROM 
    SYS.DM_DB_INDEX_PHYSICAL_STATS (DB_ID(), NULL, NULL, NULL, NULL) AS DDIPS
        INNER JOIN SYS.TABLES T ON T.OBJECT_ID = DDIPS.OBJECT_ID
        INNER JOIN SYS.SCHEMAS S ON T.SCHEMA_ID = S.SCHEMA_ID
        INNER JOIN SYS.INDEXES I ON I.OBJECT_ID = DDIPS.OBJECT_ID
        AND DDIPS.INDEX_ID = I.INDEX_ID
WHERE 
    DDIPS.DATABASE_ID = DB_ID()
    AND I.NAME IS NOT NULL
    AND DDIPS.AVG_FRAGMENTATION_IN_PERCENT > 0
ORDER BY 
    DDIPS.AVG_FRAGMENTATION_IN_PERCENT DESC


