/**LONG RUNNING TRANSACTION ON A DATABASES.**/
/**----------------------------------------**/
SELECT 
    S.SESSION_ID,
    S.LOGIN_NAME,
    R.STATUS,
    R.COMMAND,
    R.CPU_TIME,
    R.TOTAL_ELAPSED_TIME,
    R.WAIT_TYPE,
    R.WAIT_TIME,
    R.WAIT_RESOURCE,
    R.BLOCKING_SESSION_ID,
    T.TRANSACTION_ID,
    T.TRANSACTION_BEGIN_TIME,
    T.TRANSACTION_STATE,
    T.TRANSACTION_STATUS
FROM 
    SYS.DM_TRAN_ACTIVE_TRANSACTIONS T
JOIN 
    SYS.DM_TRAN_SESSION_TRANSACTIONS ST ON T.TRANSACTION_ID = ST.TRANSACTION_ID
JOIN 
    SYS.DM_EXEC_SESSIONS S ON ST.SESSION_ID = S.SESSION_ID
JOIN 
    SYS.DM_EXEC_REQUESTS R ON S.SESSION_ID = R.SESSION_ID
WHERE 
    T.TRANSACTION_BEGIN_TIME < DATEADD(MINUTE, -5, GETDATE())--ADJUST TIME HERE
    --T.TRANSACTION_BEGIN_TIME < DATEADD(SECOND, -30, GETDATE())--ADJUST TIME HERE
ORDER BY 
    T.TRANSACTION_BEGIN_TIME DESC;


