SELECT   
    S.SESSION_ID,
    R.STATUS,
    R.BLOCKING_SESSION_ID    'BLK BY',
    R.WAIT_TYPE,
    WAIT_RESOURCE,
    R.WAIT_TIME / (1000 * 60)   'WAIT M',
    R.CPU_TIME,
    R.LOGICAL_READS,
    R.READS,
    R.WRITES,
    R.TOTAL_ELAPSED_TIME / (1000 * 60)   'ELAPS M',
    SUBSTRING(ST.TEXT,(R.STATEMENT_START_OFFSET / 2) + 1,
    ((CASE 
        R.STATEMENT_END_OFFSET
        WHEN -1
        THEN DATALENGTH(ST.TEXT)
        ELSE R.STATEMENT_END_OFFSET
    END - R.STATEMENT_START_OFFSET) / 2) + 1) AS STATEMENT_TEXT,
    COALESCE(QUOTENAME(DB_NAME(ST.DBID)) + N'.' + QUOTENAME(OBJECT_SCHEMA_NAME(ST.OBJECTID,ST.DBID)) + N'.' + QUOTENAME(OBJECT_NAME(ST.OBJECTID,ST.DBID)),'') AS COMMAND_TEXT,
    R.COMMAND,
    S.LOGIN_NAME,
    S.HOST_NAME,
    S.PROGRAM_NAME,
    S.LAST_REQUEST_END_TIME,
    S.LOGIN_TIME,
    R.OPEN_TRANSACTION_COUNT
FROM     
    SYS.DM_EXEC_SESSIONS AS S
        JOIN SYS.DM_EXEC_REQUESTS AS R ON R.SESSION_ID = S.SESSION_ID
        CROSS APPLY SYS.DM_EXEC_SQL_TEXT(R.SQL_HANDLE) AS ST
WHERE   R.SESSION_ID != @@SPID
        AND R.SESSION_ID > 50
        --AND HOST_NAME = 'RMPROD'
ORDER BY   
    R.CPU_TIME DESC,
    R.STATUS,
    R.BLOCKING_SESSION_ID,
    S.SESSION_ID

