/**CPU CORES USED BY SQL SERVERS**/
/**-----------------------------**/
SELECT * 
FROM SYS.DM_OS_SCHEDULERS
WHERE STATUS='VISIBLE ONLINE'
/**OR**/
SELECT * 
FROM SYS.DM_OS_SCHEDULERS
WHERE SCHEDULER_ID = CPU_ID    

/**CPU CORES NOT USED BY SQL SERVERS**/
/**---------------------------------**/
SELECT * 
FROM SYS.DM_OS_SCHEDULERS
WHERE STATUS='VISIBLE OFFLINE'




