SELECT 
	DM_WS.WAIT_DURATION_MS,
	DM_WS.WAIT_TYPE,
	DM_ES.STATUS,
	DM_T.TEXT,
	DM_QP.QUERY_PLAN,
	DM_WS.SESSION_ID,
	DM_ES.CPU_TIME,
	DM_ES.MEMORY_USAGE,
	DM_ES.LOGICAL_READS,
	DM_ES.TOTAL_ELAPSED_TIME,
	DM_ES.PROGRAM_NAME,
	DB_NAME(DM_R.DATABASE_ID) DATABASENAME,
	-- OPTIONAL COLUMNS
	DM_WS.BLOCKING_SESSION_ID,
	DM_R.WAIT_RESOURCE,
	DM_ES.LOGIN_NAME,
	DM_R.COMMAND,
	DM_R.LAST_WAIT_TYPE
FROM 
	SYS.DM_OS_WAITING_TASKS DM_WS
INNER JOIN 
	SYS.DM_EXEC_REQUESTS DM_R ON DM_WS.SESSION_ID = DM_R.SESSION_ID
INNER JOIN 
	SYS.DM_EXEC_SESSIONS DM_ES ON DM_ES.SESSION_ID = DM_R.SESSION_ID
CROSS APPLY 
	SYS.DM_EXEC_SQL_TEXT (DM_R.SQL_HANDLE) DM_T
CROSS APPLY 
	SYS.DM_EXEC_QUERY_PLAN (DM_R.PLAN_HANDLE) DM_QP
--WHERE DM_ES.IS_USER_PROCESS = 1
