/**TO SYNC LOGINS IN AOAG FROM PRIMARY TO SECONDARY**/ 
/**------------------------------------------------**/
--TO GET THE USER WITH SAME SID RUN THIS ON PRIMARY AND THEY RUN THE OUTPUT OF THIS ON SECONDARY
SELECT 
    N'CREATE LOGIN ['+SP.[NAME]+'] WITH PASSWORD=0X'+ CONVERT(NVARCHAR(MAX), L.PASSWORD_HASH, 2)+N' HASHED, '+N'SID=0X'+CONVERT(NVARCHAR(MAX), SP.[SID], 2)+N';'  
FROM 
    MASTER.SYS.SERVER_PRINCIPALS AS SP  
        INNER JOIN MASTER.SYS.SQL_LOGINS AS L ON SP.[SID]=L.[SID]  
WHERE 
    SP.NAME='SECLORE_OWNER' -- CHANGE THE USER NAME HERE

