/**TO RESTORE/REFRESH THE DATABASE USE BELOW.**/
/**------------------------------------------**/
SP_HELPDB [DB_NAME]
GO
RESTORE FILELISTONLY FROM DISK = '\\PATH WHERE THE BACKUP NEED TO BE STORED\DB_NAME_DDMMYYYY_FULL.BAK|.TRN'
GO
ALTER DATABASE [DB_NAME] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
USE MASTER
GO
RESTORE DATABASE [DB_NAME] FROM DISK = '\\PATH WHERE THE BACKUP NEED TO BE STORED\DB_NAME_DDMMYYYY_FULL.BAK|.TRN'
WITH REPLACE,
MOVE '<SOURCE FILE LOGICAL NAME FROM BACKUP FILE>' TO '<PATH AND FILE NAME OF DEST>',
MOVE '<SOURCE FILE LOGICAL NAME FROM BACKUP FILE>' TO '<PATH AND FILE NAME OF DEST>',
MOVE '<SOURCE FILE LOGICAL NAME FROM BACKUP FILE>' TO '<PATH AND FILE NAME OF DEST>'

/**TO TAKE BACKUP OF A DATABASES TO URL USE BELOW**/
/**----------------------------------------------**/
-->TAKE THE PATH OR URL FROM THE JOBS AND MAKE IT FEASIBLE.
BACKUP DATABASE <DATABASE_NAME>
TO URL = 'HTTPS://ABCD.BLOB.CORE.WINDOWS.NET/AZUSQL/AZUSQLPROD_DIFF_20220905_180000.BAK'
WITH DIFFERENTIAL,
CREDENTIAL= '<GET THE CREDS FROM SERVER IN CREDENTIAL TAB>'

/**TO RESTORE A DATABASE FROM URL USE BELOW**/
/**----------------------------------------**/
SP_HELPDB [DB_NAME]
GO
RESTORE FILELISTONLY FROM URL = '\\PATH WHERE THE BACKUP NEED TO BE STORED\DB_NAME_DDMMYYYY_FULL.BAK|.TRN'
WITH CREDENTIAL= 'XXXXXX'

/**TO RESTORE A DATABASE FROM URL USE BELOW**/
/**----------------------------------------**/
ALTER DATABASE [<DESTINATION DB NAME>] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
USE MASTER
GO
RESTORE DATABASE <DATABASE NAME>
FROM URL = 'HTTPS://ABCD.BLOB.CORE.WINDOWS.NET/AZUSQL/AZU20220905_180000.BAK'
WITH CREDENTIAL= 'XXXXXX',
MOVE '<SOURCE FILE LOGICAL NAME FROM BACKUP FILE>' TO '<PATH AND FILE NAME OF DESTINATION>',
MOVE '<SOURCE FILE LOGICAL NAME FROM BACKUP FILE>' TO '<PATH AND FILE NAME OF DESTINATION>',
MOVE '<SOURCE FILE LOGICAL NAME FROM BACKUP FILE>' TO '<PATH AND FILE NAME OF DESTINATION>'
REPLACE, STATS=1


